name: Deploy Docs

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # If you're using submodules

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Generate Documentation for Each Subfolder
      run: |
        for dir in */; do
          if [ -f "$dir/Cargo.toml" ]; then
            echo "Generating documentation in $dir"
            (cd $dir && cargo doc --no-deps)
          else
            echo "Skipping $dir, no Cargo.toml found"
          fi
        done

    - name: Create Aggregated Documentation Index
      run: |
        echo "<html><head><title>Aggregated Documentation</title></head><body>" > target/doc/index.html
        for dir in */target/doc; do
          if [ -d "$dir" ]; then
            project_name=$(basename $(dirname $dir))
            echo "<a href='$project_name/index.html'>$project_name</a><br>" >> target/doc/index.html
          fi
        done
        echo "</body></html>" >> target/doc/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
