name: Rustfmt

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Ensures that all submodules are checked out recursively
          submodules: 'recursive'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      # Iterate over each submodule to run rustfmt or make format
      - name: Run rustfmt in submodules
        run: |
          for dir in */; do
            if [ -d "$dir" ]; then
              echo "Running rustfmt in $dir"
              cd $dir
              # Check for a Makefile or Cargo.toml to determine how to run rustfmt
              if [ -f "Makefile" ]; then
                make format
              elif [ -f "Cargo.toml" ]; then
                cargo fmt -- --check
              else
                echo "No Makefile or Cargo.toml found in $dir, skipping..."
              fi
              cd ..
            fi
          done
